ablyApiKey: INSERT_YOUR_API_KEY_HERE
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: INSERT_YOUR_AUTH0_CLIENTID_HERE
            client-secret: INSERT_YOUR_AUTH0_CLIENT_SECRET_HERE
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://INSERT_YOUR_AUTH0_URI_HERE/
